version: '3.3'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'todo'
      MYSQL_USER: 'todo'
      MYSQL_PASSWORD: 'todo'
      MYSQL_ROOT_PASSWORD: 'todo'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: